import './globals.css'
import { Inter } from 'next/font/google'
import Nav from './components/Nav'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>title blog</title>
      <meta content='width=device-width, initial-scale=1'></meta>
      <link rel="icon" href="/favicon.ico"></link>
      <body className={inter.className}>
        <Nav />
        {children}
      </body>
    </html>
  )
}
